server:
  port: ${PORT:0}
spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
logging:
  level:
    org.springframework.web: ERROR
    ru.leodev: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: .\\log_file.log


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
gateway:
  ip: 192.168.2.81
token:
  expiration_time: 864000000
  secret: h3na6fhtp02lxfgawga