server:
  port: ${PORT:0}
spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}