server:
  port: 8011
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    instance-id: ${spring.application.name}

api.registration.url.path: /users-ws/users
api.login.url.path: /users-ws/users/login
api.h2console.url.path: /users-ws/h2-console/**

authorization.token.header.name: Authorization
authorization.token.header.prefix: Bearer
token.secret: h3na6fhtp02lxfgawga